<div>
<img src="Imgs/logo-numpy.svg" width="250"/>
</div>

https://numpy.org

- Abreviação para Numerical Python
- É base para muitos outros pacotes, inclusive pacotes de Machinle Learning 
- Utilizado para computação de alta performance 
- Utilizado para analise e transformação de dados
- É utilizado frequentemente em conjunto com Pandas (Próximo tema)

In [3]:
import numpy as np
import random 

#### Boolean e Seleções Avançadas

Conceito super importante no numpy e no pandas é o de máscara booleana.
<br>
Ao aplicar qualquer operador booleanoo numpy retorna um array de True e False no qual ele aplicou elemento a elemento aquele operador.

- '>'
- '<'
- '<='
- '>='
- '=='
- 'in'




In [44]:
#Array 2d
arr1 = np.array([[1, 10, 20, 30],[1,2,50,13]])
print(arr1)

[[ 1 10 20 30]
 [ 1  2 50 13]]


In [45]:
#boolean simples, retorna a mesma array com True e False
arr1 >10

array([[False, False,  True,  True],
       [False, False,  True,  True]])

In [46]:
#Quando colocamos cochetes ele retorna os valores nos quais o nosso boolean é verdadeiro 
arr1[arr1 > 10]

array([20, 30, 50, 13])

In [47]:
#comparando arrays 1D
a = np.array([1,2,3,4]) 
b = np.array([3,8,5,6])

#funções
np.greater(a, b)
np.less(a, b)
np.equal(a, b)
np.not_equal(a, b)

array([ True,  True,  True,  True])

In [48]:
# .any & .all
#coluna
np.any(arr1 > 10, axis=0)
#linea
np.any(arr1 > 10, axis=1)

array([ True,  True])

In [49]:
#filtro boolean and &
filtand = (arr1 > 10) & (arr1 <= 20)
filtand

array([[False, False,  True, False],
       [False, False, False,  True]])

In [51]:
#filtro boolean 2
filtand2 = (arr1 > 15) & (arr1 % 2 == 0)

In [52]:
#podemos gerar um filtro com o resultado da nossa pergunta booleana 
arr1[filtand]

array([20, 13])

In [53]:
# filtro boolean or |
filtor = (arr1 > 10) | (arr1 <= 20)
filtor

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [54]:
#Pegar valores do filtro 
arr1[filtor]

array([ 1, 10, 20, 30,  1,  2, 50, 13])

In [55]:
#Filtro not 
filt = ~(arr1 == 1) 

In [56]:
filt

array([[False,  True,  True,  True],
       [False,  True,  True,  True]])

In [57]:
filtro2 = (arr1 > 15) & (arr1 % 2 == 0)
 
# array nova sobre as condições do filtro
new_arr = arr1[filtro2]

In [58]:
new_arr

array([20, 30, 50])

In [59]:
arr = np.array([x for x in range(11, 40)])
 
print(arr)
 
# lambda + condition
# A função filter extrai elementos de um iteravel e retorna True ou False
new_arr = list(filter(lambda x: x > 15 and x % 2 == 0 and x % 10 != 0, arr))
 
# Converting new list into numpy array
new_arr = np.array(new_arr)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39]


#### Vstack e Reorganizando Arrays

In [60]:
#reshape em uma array 1D
np.array([12, 12, 23, 34]).reshape(2, 2)

array([[12, 12],
       [23, 34]])

In [61]:
#invert no array
a = np.array((12, 12, 23, 34, 2))
b = np.invert(a)
print(b)

[-13 -13 -24 -35  -3]


In [103]:
#Vstack em duas arrays do mesmo tamanho
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
print(a1)
print(a2)
vstack = np.vstack([a1,a2])
print(vstack)
vstack2 = np.vstack([vstack, vstack])
print(vstack2)


[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [104]:
a1.shape

(4,)

In [109]:
vstack2 = np.vstack([a1,a2,a2,a2])
print(vstack2)

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [114]:

vstack2 = np.array([
        [[1, 2], [3, 4], [5, 6], [7, 8]],
        [[9, 10], [11, 12], [13, 14], [15, 16]]])
print(vstack2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [117]:
#flatten order= C(por linha), F(por coluna)
vstack2.flatten('C')
vstack2.flatten('F')

array([ 1,  9,  3, 11,  5, 13,  7, 15,  2, 10,  4, 12,  6, 14,  8, 16])

##### DIY 1

1. Crie 3 arrays 1D com 10 elementos com numeros inteiros de 1 a 10  e printe elas (dica = randint)
2. Elabore um filtro boolean na arr 1 com &, pegue os valores do array com o filtro e printe
3. Elabore um filtro boolean na arr 2 com |, pegue os valores do array com o filtro e printe
4. Faça um reshape na arr1 
5. Façã um vstack com as arr2 e arr3
6. Aplique um flatten por linha na array nova

In [121]:
#1
diy_array1 = np.random.randint(11, size = 10)
diy_array2 = np.random.randint(11, size = 10)
diy_array3 = np.random.randint(11, size = 10)

print(diy_array1)
print(diy_array2)
print(diy_array3)

[ 1  0  4  3  8  7 10  5  5  0]
[ 8  1  8  0  8  7  7 10  0  7]
[ 7 10  1  6  4  4  8  6  3  8]


In [128]:
#2 
filtand = (diy_array1 % 2 == 0) & (diy_array1 > 5)
print(diy_array1[filtand])

#3
filtor = (diy_array1 % 2 == 0) | (diy_array1 > 5)
print(diy_array1[filtor])

#4
diy_array1 = diy_array1.reshape(5,2)
print(diy_array1)

#5
diy_vstack = np.vstack([diy_array2, diy_array3])
print(diy_vstack.shape)
print(diy_vstack)

#6
flatten = diy_vstack.flatten('C')
print(flatten)

[ 8 10]
[ 0  4  8  7 10  0]
[[ 1  0]
 [ 4  3]
 [ 8  7]
 [10  5]
 [ 5  0]]
(2, 10)
[[ 8  1  8  0  8  7  7 10  0  7]
 [ 7 10  1  6  4  4  8  6  3  8]]
[ 8  1  8  0  8  7  7 10  0  7  7 10  1  6  4  4  8  6  3  8]


In [21]:
#1
diy_array1 = np.random.randint(1, 11, 10)
diy_array2 = np.random.randint(1, 11, 10)
diy_array3 = np.random.randint(1, 11, 10)
print(diy_array1)
print(diy_array2)
print(diy_array3)

[10  4  7  4  1  5  2  1  5  6]
[ 1  4 10  2  1  9  2  1  6  7]
[ 8 10  8  7  7  1  5 10  1  7]


In [23]:
#2
diy_filterand = (diy_array1 > 5) & (diy_array2 > 5) & (diy_array3 > 5)
print(diy_filterand)
print(diy_array3[diy_filterand])

#3
diy_filteror = (diy_array1 > 5) | (diy_array2 > 5) | (diy_array3 > 5)
print(diy_filteror)
print(diy_array3[diy_filteror])

#4
diy_array1_copy = diy_array1.copy()
diy_array1_copy = diy_array1_copy.reshape(2,-1)
print(diy_array1_copy)

#5
diy_vstack = np.vstack([diy_array2, diy_array3])
print(diy_vstack)

#6
print(diy_vstack.flatten('C')) #linha
print(diy_vstack.flatten('F')) #coluna
print(diy_vstack)


[False False  True False False False False False False  True]
[8 7]
[ True  True  True  True  True  True False  True  True  True]
[ 8 10  8  7  7  1 10  1  7]
[[10  4  7  4  1]
 [ 5  2  1  5  6]]
[[ 1  4 10  2  1  9  2  1  6  7]
 [ 8 10  8  7  7  1  5 10  1  7]]
[ 1  4 10  2  1  9  2  1  6  7  8 10  8  7  7  1  5 10  1  7]
[ 1  8  4 10 10  8  2  7  1  7  9  1  2  5  1 10  6  1  7  7]
[[ 1  4 10  2  1  9  2  1  6  7]
 [ 8 10  8  7  7  1  5 10  1  7]]


#### Numpy Matrix

> Marizes em são obrigatoriamente elementos de duas dimensões 

In [129]:
mat1 = np.matrix([[1, 2],[3, 4]])

In [130]:
arr1 = np.array([5,6,7,8])

In [131]:
type(arr1)

numpy.ndarray

In [132]:
type(mat1)

numpy.matrix

In [133]:
mat1.ndim

2

In [136]:
#Se eu passar uma lista simples ele cria automaticamente uma matriz de duas dim
mat2 = np.matrix([1, 2, 3])
print(mat2)

[[1 2 3]]


In [135]:
mat2.ndim

2

In [137]:
#tentando criar uma matrix maior 
np.matrix([[[1, 2], [3, 4]], 
          [[5, 6], [7, 8]], 
          [[9, 10], [11, 12]]])

ValueError: matrix must be 2-dimensional

In [138]:
arr2 = np.array([[[1, 2], [3, 4]], 
          [[5, 6], [7, 8]], 
          [[9, 10], [11, 12]]])

In [139]:
#bloco, linha, coluna
print(arr2.ndim)
print(arr2.shape)

3
(3, 2, 2)


In [142]:
#array multi Element Wise
a = np.array([[1, 2], 
             [3, 4]])
b = np.array([[5, 6], 
             [8, 9]])
print(a * b)
print(np.matmul(a,b))

[[ 5 12]
 [24 36]]
[[21 24]
 [47 54]]


In [141]:
#matriz * Dot Product
c = np.matrix([[1, 2], 
              [3, 4]])
d = np.matrix([[5, 6], 
              [8, 9]])
print(c)
print(d)
print(c * d)

[[1 2]
 [3 4]]
[[5 6]
 [8 9]]
[[21 24]
 [47 54]]


<div>
<img src="Imgs/dotprod.jpeg" width="500"/>
</div>

In [143]:
#Soma e subtração 
print(c+d)
print(d-c)
print(c/d)

[[ 6  8]
 [11 13]]
[[4 4]
 [5 5]]
[[0.2        0.33333333]
 [0.375      0.44444444]]


> It is no longer recommended to use the matrix class, even for linear algebra. Instead, use regular numpy arrays. The matrix class may be removed in the future. (05-2021)

##### DIY 

1. Crie uma matriz com numeros aleatorios de 1 ao 20 shape (2,2)
2. Crie um array 2D com shape (2,2)
3. Transforme a array em matrix 
4. Printe o type do array transformado
5. Faça o Dot product das matrizes


In [148]:
#1
matrix = np.matrix(np.random.randint(1,21,4)).reshape(2,2)
print(matrix)

#2
array_2d = np.random.randint(1,21,4).reshape(2,2)
print(array_2d)

[[13  1]
 [ 7  1]]
[[17 17]
 [10  9]]


In [154]:
#3
matrix2 = np.matrix(array_2d)
print(matrix2)
#4
print(type(matrix2))
#5
print(matrix * matrix2)

[[17 17]
 [10  9]]
<class 'numpy.matrix'>
[[231 230]
 [129 128]]


In [34]:
#1
diy_matrix = np.matrix(np.random.randint(1, 21, 4)).reshape(2,2)
print(diy_matrix)

#outra forma:
# diy_matrix = np.matrix(np.random.randint(21, size=(2, 2)))

[[ 1 13]
 [ 5 13]]


In [35]:
#2
diy_arr = np.random.randint(1, 21, 4).reshape(2,2)
print(diy_arr)

[[14  6]
 [16  4]]


In [36]:
#3
diy_matrix2 = np.matrix(diy_arr)
print(diy_matrix2)

#4
print(type(diy_matrix2))

#5
print(diy_matrix*diy_matrix2)

[[14  6]
 [16  4]]
<class 'numpy.matrix'>
[[222  58]
 [278  82]]


#### Grupo

https://archive.ics.uci.edu/ml/datasets/Wine+Quality

1. Importe o mesmo dataset da aula passada 
2. Selecione as mesmas colunas Citric Acid, PH e  Alcohol
3. Faça um filtro booleano com os vinhos com:
    - um valor maior ou igual a 6 de Alcohol
    - um valor de PH menor do que 3
    - um valor de Citric Acid maior do que .20
4. Faça um novo array com esses dados 
5. Quantos vinhos tem a nossa seleção?
6. Quantos vinhos deixamos de fora?
7. Faça um outro filtro segundo a sua criatividade 
8. Qual a sua conclusão?

In [7]:
#1 e #2 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
wine_arr = np.genfromtxt(url, delimiter=';', usecols=[2,8,10], skip_header = True)

#3 col0 = acid, col1 =pH , col 2=alcool
filtro = (wine_arr[:,2] >= 6) & (wine_arr[:,1] <= 3) & (wine_arr[:,0] > .20)

#4 
new_wine_arr = wine_arr[filtro]

#5
print(len(new_wine_arr))

#6
print(f"Foram deixados de fora: {(wine_arr.shape[0] - new_wine_arr.shape[0])}")

#7
filtro2 = (wine_arr[:,1] <= 3)
wine_filt2 = wine_arr[filtro2]
print(f"Dataset original: {(wine_arr.shape[0])}")
print(f"Foram deixados de fora: {(wine_arr.shape[0] - wine_filt2.shape[0])}")

#8 O pH abaixo ou igual a 3 exclui a grande maioria dos vinhos do dataset

33
Foram deixados de fora: 1566
Dataset original: 1599
Foram deixados de fora: 1564
