<div>
<img src="Imgs/logo-numpy.svg" width="250"/>
</div>

https://numpy.org

- Abreviação para Numerical Python
- É base para muitos outros pacotes, inclusive pacotes de Machinle Learning 
- Utilizado para computação de alta performance 
- Utilizado para analise e transformação de dados
- É utilizado frequentemente em conjunto com Pandas (Próximo tema)

Curiosidade sobre Numpy
https://numpy.org/case-studies/blackhole-image/

In [4]:
import numpy as np

#### Conceitos principais

In [2]:
#numpy.ndarray VS Lists
list1 = [4,2,5,6,10]
array1 = np.array(list1)
print(f'List: {list1}')
print(type(list1))
print(list1)
print(type(list1[1]))
print(type(list1[4]))
print('\n')
print(f'Numpy array: {array1}')
print(f'Type: {type(array1)}')
print(array1)
print(type(array1[0]))
print(type(array1[3]))


List: [4, 2, 5, 6, 10]
<class 'list'>
[4, 2, 5, 6, 10]
<class 'int'>
<class 'int'>


Numpy array: [ 4  2  5  6 10]
Type: <class 'numpy.ndarray'>
[ 4  2  5  6 10]
<class 'numpy.int64'>
<class 'numpy.int64'>


In [5]:
# Soma de um numero na lista e no nparray
array1 + 2

array([ 6,  4,  7,  8, 12])

In [4]:
list1 + 2

TypeError: can only concatenate list (not "int") to list

>Todos os itens de um array devem ser do mesmo tipo, diferentemente os itens de uma lista. Segue!

i - integer
b - boolean
U - unsigned integer (Inteiros que não tem simbolos de + ou - associados )
f - float
c - complex float (Numeros Imaginarios)
m - timedelta
M - datetime
O - object
S - string
U - unicode string

In [6]:
#Testes com diferentes tipos
#Str>Float>Int
list2 = [[2,3,4,4],[3,40,100,0]]

In [7]:
#dtype param 
nparray2 = np.array(list2)

In [9]:
#ndim, shape, size, dtype
print(f' Array: {nparray2}')
print('\n')
print(f' Shape: {nparray2.shape}')
print(f' Dtype: {nparray2.dtype}')
print(f' Dims: {nparray2.ndim}')
print(f' Size: {nparray2.size}')
print(f' Dtype Especifica: {type(nparray2[1,2])}')

 Array: [[  2   3   4   4]
 [  3  40 100   0]]


 Shape: (2, 4)
 Dtype: int64
 Dims: 2
 Size: 8
 Dtype Especifica: <class 'numpy.int64'>


In [10]:
#astype
nparray2.astype('float')

array([[  2.,   3.,   4.,   4.],
       [  3.,  40., 100.,   0.]])

In [11]:
nparray2.dtype

dtype('int64')

In [12]:
#zeros = array feita de zeros
npzeros = np.zeros(6)
print(npzeros)
print()
#ones - array feita de qualquer numero
npones = np.ones((2,2))*10
print(npones)
print()
#empty - array dada um tamanho e tipo determinado com valores randomicos
npempty = np.empty([2,2], dtype='int')
print(npempty)
print()
#full - parecida a ones porem mais "elegante"
npfull = np.full((2, 2), 99)
print(npfull)
print()
#fulllike - cria um array baseada em uma existente com outro numero dado
nplike = np.full_like(npfull, 4)
print(nplike)
print()
# arange - cria um array com elementos separados por um step
nparange = np.arange(0, 10, .1)
print(nparange)
print()
#copias do array 
array = np.array([1, 2, 3])
copyarr = array.copy()
print(array)
print(copyarr)

[0. 0. 0. 0. 0. 0.]

[[10. 10.]
 [10. 10.]]

[[4621819117588971520 4621819117588971520]
 [4621819117588971520 4621819117588971520]]

[[99 99]
 [99 99]]

[[4 4]
 [4 4]]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]

[1 2 3]
[1 2 3]


#### Operações entre ndarrays

> Numpy foi feito para manipular e realizar operações vetorizadas em grande escala, com velocidade

In [153]:
#creating random arrays  = np.random.random_sample retorna array do tamanho pedido com numeros entre 0.0, 1.0

In [13]:
np.random.random_sample((3, 3))

array([[0.73033564, 0.40552425, 0.42633118],
       [0.28168036, 0.44976223, 0.02759368],
       [0.7444393 , 0.37057488, 0.27100324]])

In [14]:
#multipy, divide, add, subtract
#numero especifico tmb
array1 = 5*np.random.random_sample((3, 3))
array2 = 6*np.random.random_sample((3, 3))
print(array1)
print('\n')
print(array2)
print('\n')
print('Multi : \n',np.multiply(array1, array2))
print('Sub: \n',np.subtract(array1, array2))
print('Soma: \n',np.add(array1, array2))
print('Divisão: \n',np.divide(array1, array2))

[[2.02824296 4.12079731 3.77604278]
 [1.00967925 3.29216953 4.05095716]
 [2.14336166 1.49651896 4.88906365]]


[[5.95895632 4.33917931 3.72387861]
 [3.45324135 3.69240667 4.59309652]
 [3.69162347 1.2954379  4.2323701 ]]


Multi : 
 [[12.08621123 17.88087841 14.06152494]
 [ 3.48666615 12.15602872 18.60643726]
 [ 7.91248419  1.93864738 20.69232681]]
Sub: 
 [[-3.93071336 -0.21838201  0.05216417]
 [-2.44356209 -0.40023715 -0.54213936]
 [-1.54826181  0.20108107  0.65669355]]
Soma: 
 [[7.98719929 8.45997662 7.49992139]
 [4.4629206  6.9845762  8.64405369]
 [5.83498512 2.79195686 9.12143375]]
Divisão: 
 [[0.34036883 0.94967205 1.01400802]
 [0.29238595 0.89160535 0.88196648]
 [0.58060137 1.15522247 1.15515977]]


##### DIY

Ex 1
1) Transforme a duas listas em duas arrays diferentes arr1 e arr2.
2) Verifique o dtype dos array
3) Transforme os dois array em float
4) Compare as duas arrays e mostre os indices dos elementos que são iguais(dica = .where)
5) Retorne os numeros do array que são iguais usando o output do paso 4 dica subsetting

In [17]:
list_1 = [1,2,3,4,5]
list_2 = [1,3,2.2,4,5]

#1
arr1 = np.array(list_1)
arr2 = np.array(list_2)
#2
print(arr1.dtype)
print(arr2.dtype)
#3
print(arr1.astype(float))
print(arr2.astype(float))
#4
print(np.where(arr1 == arr2))
#5
print(arr1[[0,3,4]])

int64
float64
[1. 2. 3. 4. 5.]
[1.  3.  2.2 4.  5. ]
(array([0, 3, 4]),)
[1 4 5]


#### Indexação, Slicing

In [5]:
array = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
array

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [6]:
#seleção por index [linha, coluna]
#numero especifico
print(array[1,5])
#numero especifico negativo
print(array[1, -2])

# : é chamado de slicing [startindex:endindex:stepsize]
#primera linha
print(array[0, :])
#todos os elementos da 2 coluna
print(array[:, 2])
#elemento especificos com step
print(array[0,1:6:2])

13
13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]


> conseguimos mudar também elementos especificos de uma array usando index e slicing

In [7]:
#trocando um numero especifico
array[1,5] = 20
print(array)
#trocar coluna inteira 
array[:, 2] = 5
print(array)
#voltar os valores originais 
array[:, 2] = [3, 10]
print(array)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


#### DIY

Ex 2
1) Gere uma array com 3 dimensões com shape. (2,2,2)
2) Printe o ndim da array e o shape
3) Retire um elemento especifico [bloco][linha][coluna]



In [9]:
#1 
array3d= np.array([[[1, 2], [3,4]],[[6,8],[0,7]]])

#2
print(array3d)
print(array3d.ndim)
print(array3d.shape)

#3
print(array3d[1,1,1])

[[[1 2]
  [3 4]]

 [[6 8]
  [0 7]]]
3
(2, 2, 2)
7


##### Dica

O array 3D é um conjunto de arrays de duas dimensões, "um array de arrays de arrays", os elementos são acessados para um indice para linha, um para coluna um para o bloco ( Parecido com um cubo). Tem apliações em diversas areas como: Jogos, Data Wharehouses, Analise de dados entre outros. 

Ordem [bloco][linha][coluna]

<div>
<img src="Imgs/arrays.png" width="500"/>
</div>
<img src="Imgs/formato3d.png" width="500"/>

In [11]:
vetor = np.ones((4,3,2))
vetor

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### Transposição, Stacking e Redimensionamento

<img src="Imgs/transpose.png" width="500"/>

In [12]:
array = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
array

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [13]:
array.T

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13],
       [ 7, 14]])

In [21]:
array = np.array([[1,2],[3,4]])
np.matmul(array, array)

array([[ 7, 10],
       [15, 22]])

#### Estatistica

In [22]:
stats = np.array([[1, 8, 3], [4, 5, 6]])
stats

array([[1, 8, 3],
       [4, 5, 6]])

In [17]:
#minimo do nosso array
np.min(stats)

1

In [18]:
#maximo do nosso array
np.max(stats)

8

In [25]:
#minima por linha
np.min(stats, axis=1) 

array([1, 4])

In [26]:
#minima por coluna
np.max(stats, axis=0)

array([4, 8, 6])

In [24]:
#maximo de uma coluna especifica
np.max(stats[:, 1],axis=0)

8

#### DIY - Grupos

https://archive.ics.uci.edu/ml/datasets/Wine+Quality

In [27]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'

DICA = Procure por nan e substitua por 0 (dica: is_nan e nan_to_num)m

https://numpy.org/devdocs/user/basics.io.genfromtxt.html
1) Verifique a url e veja quais são as colunas do arquivo
2) Veja qual é o delimiter do arquivo ',' , ':', ';'
3) Selecione as colunas (param usecols) Citric Acid, PH e  Alcohol
4) Mostre o array e as caracteristicas dele ndim, shape, dype
5) Procure o maximo e minimo da coluna PH 
6) Obtenha a media da coluna Alcohol

In [49]:
#Import data
wine_arr = np.genfromtxt(url, delimiter=';', usecols=[2,8,10], skip_header = True)

In [57]:
#Show array
print(wine_arr)

print(wine_arr.ndim)

print(wine_arr.shape)

print(wine_arr.dtype)
print(np.isnan(wine_arr))
print(np.nan_to_num(wine_arr))


[[ 0.    3.51  9.4 ]
 [ 0.    3.2   9.8 ]
 [ 0.04  3.26  9.8 ]
 ...
 [ 0.13  3.42 11.  ]
 [ 0.12  3.57 10.2 ]
 [ 0.47  3.39 11.  ]]
2
(1599, 3)
float64
[[False False False]
 [False False False]
 [False False False]
 ...
 [False False False]
 [False False False]
 [False False False]]
[[ 0.    3.51  9.4 ]
 [ 0.    3.2   9.8 ]
 [ 0.04  3.26  9.8 ]
 ...
 [ 0.13  3.42 11.  ]
 [ 0.12  3.57 10.2 ]
 [ 0.47  3.39 11.  ]]


In [51]:
#Max e Min de pH (coluna 1)
ph_min = np.min(wine_arr[:,1])
print(f"MIN: {ph_min}")
ph_max = np.max(wine_arr[:,1])
print(f"MAX: {ph_max}")

MIN: 2.74
MAX: 4.01


In [52]:
#média alcool (coluna 2)
alcool_med = np.average(wine_arr[:,2])
print(f"MÉDIA ALCOOL: {alcool_med}")

MÉDIA ALCOOL: 10.422983114446529


In [53]:
# Max Min Avg PH
print(np.min(wine_arr[:,1]))
print(np.max(wine_arr[:,1]))
print(np.average(wine_arr[:,1]))
print(np.std(wine_arr[:,1]))

# Max Min Avg Alcool
print(np.min(wine_arr[:,2]))
print(np.max(wine_arr[:,2]))
print(np.average(wine_arr[:,2]))
print(np.std(wine_arr[:,2]))

# Max Min Avg Acido Citrico
print(np.min(wine_arr[:,0]))
print(np.max(wine_arr[:,0]))
print(np.average(wine_arr[:,0]))
print(np.std(wine_arr[:,0]))

2.74
4.01
3.3111131957473416
0.15433818141060165
8.4
14.9
10.422983114446529
1.0653343003437483
0.0
1.0
0.2709756097560976
0.19474021445233364


#### Extra

1) Faça um for loop que itere por todos os elementos de uma array de 3 dimensões

In [313]:
array3d= np.array([[[1, 2], [3,4]],[[6,8],[0,7]]])
for b in range (2):
    for c in range (2):
        for l in range (2):
            print(f'Bloco {b} ,Linha {l} ,Coluna {c} - Elemento: {array3d[b][l][c]}')

Bloco 0 ,Linha 0 ,Coluna 0 - Elemento: 1
Bloco 0 ,Linha 1 ,Coluna 0 - Elemento: 3
Bloco 0 ,Linha 0 ,Coluna 1 - Elemento: 2
Bloco 0 ,Linha 1 ,Coluna 1 - Elemento: 4
Bloco 1 ,Linha 0 ,Coluna 0 - Elemento: 6
Bloco 1 ,Linha 1 ,Coluna 0 - Elemento: 0
Bloco 1 ,Linha 0 ,Coluna 1 - Elemento: 8
Bloco 1 ,Linha 1 ,Coluna 1 - Elemento: 7
