## Exercícios Aulas 1 a 4
Prof Roger Rendón

In [2]:
#Imports
import numpy as np
import pandas as pd

#### Numpy.

1. Gere uma array randomica de 10 elementos com duas dimensões, e explore o array (ndim, dtype e shape). 

In [4]:
array_rand = np.random.randint(0,10,size = 10).reshape(2,-1)
# array_rand = (np.random.random_sample((5,2))*11).astype('int')
array_rand

array([[1, 2, 8, 8, 4],
       [9, 9, 1, 2, 1]])

In [6]:
print(f"Número de dimensões: {array_rand.ndim}")
print(f"Dtype: {array_rand.dtype}")
print(f"Shape: {array_rand.shape}")

Número de dimensões: 2
Dtype: int64
Shape: (2, 5)


2. Verifique os elementos da array e veja se tem valores NaN e transforme os valores NaN pra número

In [19]:
a =  np.array([1, 0, np.nan, 6.0])
a

array([ 1.,  0., nan,  6.])

In [20]:
print("True se há NaN no array, False caso contrário")
print(any(np.isnan(a)))

True se há NaN no array, False caso contrário
True


In [21]:
a = np.nan_to_num(a)
a

array([1., 0., 0., 6.])

3. Gere duas arrays de uma dimensão com 10 elementos cada, valores entre 1 e 50. 

    3a. Faça comparações entre as duas matrizes ( >, <, equal)

In [22]:
array_1 = np.random.randint(1,50,size = 10)
array_2 = np.random.randint(1,50,size = 10)
print(f"Array 1: {array_1}")
print(f"Array 2: {array_2}")

Array 1: [26 39 21  2 17  5 15  1  2  7]
Array 2: [26 48 10  6  5 40 33 22 28 39]


In [23]:
eh_maior = array_1 > array_2
eh_menor = array_1 < array_2
eh_igual = array_1 == array_2

print(f"É maior: {eh_maior}")
print(f"É menor: {eh_menor}")
print(f"É igual: {eh_igual}")

É maior: [False False  True False  True False False False False False]
É menor: [False  True False  True False  True  True  True  True  True]
É igual: [ True False False False False False False False False False]


In [24]:
print(f"Elementos maiores em arr1 do que arr2: {array_1[eh_maior]}")
print(f"Elementos menores em arr1 do que arr2: {array_1[eh_menor]}")
print(f"Elementos iguais em ambos: {array_1[eh_igual]}")

Elementos maiores em arr1 do que arr2: [21 17]
Elementos menores em arr1 do que arr2: [39  2  5 15  1  2  7]
Elementos iguais em ambos: [26]


4. Faça uma array com arange de 12 elementos e de o reshape correto nele.

    4a. Salve sua array em um arquivo de texto (Dica = Save Text and Headers)

In [ ]:
vetor_c = np.arange(0,24,2)

In [38]:
# vetor_c = np.arange(0,24,2)
array_12 = np.arange(12).reshape(3,4)
np.savetxt('array.txt', array_12, fmt = '%d', header='col1,col2,col3,col4', comments = "", delimiter = ",")

In [39]:
df1 = pd.read_csv('array.txt', sep=",")
df1

col1  col2  col3  col4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11

5. Carregue o arquvio da array anterior e faça uma subseleções:

    5a. Elemento na linha 1 coluna 1 

    5b. Elementos na coluna 2

    5c. Elementos na linha 2 e escolha o maximo valor dessa seleção
    
    5d. Uma array nova com o resultado de uma seleção complexa ex. (arr1 > 3) & (arr1 % 2 == 0)
    

In [44]:
load_arr = np.loadtxt('array.txt', delimiter = ',', skiprows = 1)
load_arr 

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [50]:
print(f"Elemento na linha 1 e coluna 1: {load_arr[1,1]}")
print(f"Elemento na coluna 2: {load_arr[:,2]}")
print(f"Elemento máximo na linha 2: {load_arr[2,:].max()}")

selecao = load_arr[(load_arr > 3) & (load_arr % 2 == 0)]
print(f"Resultado da seleção: {selecao}")

Elemento na linha 1 e coluna 1: 5.0
Elemento na coluna 2: [ 2.  6. 10.]
Elemento máximo na linha 2: 11.0
Resultado da seleção: [ 4.  6.  8. 10.]


6. Gere duas arrays em formato de matriz e faça um dot product nela 

In [51]:
#usando np.matrix
matrix1 = np.matrix(np.random.randint(0,4,size = 4).reshape(2,2))
matrix2 = np.matrix(np.random.randint(0,4,size = 4).reshape(2,2))
print(matrix1)
print(matrix2)

print("Produto")
print(matrix1*matrix2)

[[2 3]
 [1 3]]
[[3 0]
 [3 0]]
Produto
[[15  0]
 [12  0]]


In [54]:
#usando np.array
matrix_1 = np.random.randint(0,4,size = 4).reshape(2,2)
matrix_2 = np.random.randint(0,4,size = 4).reshape(2,2)
print(matrix_1)
print(matrix_2)

print("Produto")
print(np.matmul(matrix_1,matrix_2))

[[1 2]
 [2 0]]
[[2 3]
 [1 1]]
Produto
[[4 5]
 [4 6]]


#### Pandas

1. Faça uma pandas Series com valores inteiros randomicos de tamanho 30 de numeros entre 5 e 15

    1a. Divida sua serie em duas partes e gere duas series novas 

    1b. Adicione 5 valores a cada serie e mantenha os dois elementos como series

    1c. Conte as aparições de cada elemento da Serie

    1d. Faça comparações booleanas entre as duas series

    1e. Junte as duas series em um dataframe

    1f. Rename nas colunas utilizando inplace 
    
    1g. Explore seu novo DataFrame

In [57]:
#1
serie = pd.Series(np.random.randint(5,16,size=30))
print(serie)

#1a
serie1 = serie[:15].copy()
serie2 = serie[15:].copy().reset_index(drop=True)
print(serie1)
print(serie2)

0     14
1      5
2     10
3     10
4     10
5     15
6     11
7      5
8     12
9      5
10     9
11     6
12     8
13    15
14    14
15     5
16    14
17    14
18     6
19    15
20    12
21     6
22    10
23    15
24    12
25    15
26     8
27     6
28    15
29     5
dtype: int64
0     14
1      5
2     10
3     10
4     10
5     15
6     11
7      5
8     12
9      5
10     9
11     6
12     8
13    15
14    14
dtype: int64
0      5
1     14
2     14
3      6
4     15
5     12
6      6
7     10
8     15
9     12
10    15
11     8
12     6
13    15
14     5
dtype: int64


In [67]:
#1b
novo_array1 = pd.Series([20,21,22,23,24])
novo_array2 = pd.Series([25,26,27,28,29])
serie1 = pd.concat([serie1, novo_array1]).reset_index(drop=True)
serie2 = pd.concat([serie2, novo_array2]).reset_index(drop=True)
print(serie1)
print(serie2)

0     14
1      5
2     10
3     10
4     10
5     15
6     11
7      5
8     12
9      5
10     9
11     6
12     8
13    15
14    14
15    20
16    21
17    22
18    23
19    24
20    20
21    21
22    22
23    23
24    24
25    20
26    21
27    22
28    23
29    24
30    20
31    21
32    22
33    23
34    24
dtype: int64
0      5
1     14
2     14
3      6
4     15
5     12
6      6
7     10
8     15
9     12
10    15
11     8
12     6
13    15
14     5
15    25
16    26
17    27
18    28
19    29
20    25
21    26
22    27
23    28
24    29
25    25
26    26
27    27
28    28
29    29
30    25
31    26
32    27
33    28
34    29
dtype: int64


In [68]:
#1c
print(serie1.value_counts())
print(serie2.value_counts())

20    4
21    4
22    4
23    4
24    4
5     3
10    3
14    2
15    2
11    1
12    1
9     1
6     1
8     1
dtype: int64
15    4
25    4
26    4
27    4
28    4
29    4
6     3
5     2
14    2
12    2
10    1
8     1
dtype: int64


In [79]:
#1d
filtro1 = serie1>serie2
filtro2 = serie1 != serie2
print(serie1[filtro1])
print(serie2[filtro2])

#1e
dataframe1 = pd.concat([serie1,serie2], axis=1)
print(dataframe1)

#1f
dataframe1.rename(columns={0:'Série 1', 1: 'Série 2'}, inplace=True)
print(dataframe1)

0     14
3     10
5     15
6     11
12     8
14    14
dtype: int64
0      5
1     14
2     14
3      6
4     15
5     12
6      6
7     10
8     15
9     12
10    15
11     8
12     6
14     5
15    25
16    26
17    27
18    28
19    29
20    25
21    26
22    27
23    28
24    29
25    25
26    26
27    27
28    28
29    29
30    25
31    26
32    27
33    28
34    29
dtype: int64
     0   1
0   14   5
1    5  14
2   10  14
3   10   6
4   10  15
5   15  12
6   11   6
7    5  10
8   12  15
9    5  12
10   9  15
11   6   8
12   8   6
13  15  15
14  14   5
15  20  25
16  21  26
17  22  27
18  23  28
19  24  29
20  20  25
21  21  26
22  22  27
23  23  28
24  24  29
25  20  25
26  21  26
27  22  27
28  23  28
29  24  29
30  20  25
31  21  26
32  22  27
33  23  28
34  24  29
    Série 1  Série 2
0        14        5
1         5       14
2        10       14
3        10        6
4        10       15
5        15       12
6        11        6
7         5       10
8        12       15
9       

2. Carregue o dataset da url (https://www.kaggle.com/datasets/andrewmvd/global-monkeypox-cases)

    2a. Explore seu dataframe

    2b. Faça uma lista com todas as colunas disponíveis 

    2c. Veja todos os paises que tem no dataframe

    2d. Faça um groupby pais e veja quantos casos tem cada pais, gere um novo df com essa informação
    
    2e. Faça um groupby por status e pais e veja quantos casos confirmados tem por pais


3. Opcional(vamos discutir em aula)

    3a. O que vocês fariam com a coluna Idade?
    
    3b. Faça o tratamento de acordo com a sua linha de pensamento
    
    3c. Esse tratamento que fez é útil (Sim / Não e Por que)?
    
    3d. O que podemos fazer com essa informação para ter um dado mais acertivo?